### ISSUE TITLE
上传文件失败

### ISSUE THREAD

**Issue by runninglee** [peinhu/AetherUpload-Laravel#100]
文件 Hash 完成之后，上传到最后 接口 aetherupload/uploading 返回 Nginx 405 Not Allowed是什么情况？

**Comment by peinhu** [comment]
是不是nginx配置有问题，还是用了什么常驻内存的东西？换apache试试。
是跨域上传还是什么？没看到具体操作流程，无法复现你说的问题。

**Comment by peinhu** [comment]
这个不是PHP程序报的错，nginx报的错不太好排查的，可能是多种原因，nginx 405 not allowed应该是比较常见的错误，你网上搜一下看看可能是什么原因。

**Comment by runninglee** [comment]
改成 jquery form了
