### ISSUE TITLE
请问怎么更好的去掉web中间件

### ISSUE THREAD

**Issue by lwhdev** [peinhu/AetherUpload-Laravel#110]
目前项目是前后端分离的,我要修改源码去掉web中间件,感觉这样不好,如何避免直接修改中间件,有没有更好的办法,谢谢大佬

**Comment by peinhu** [comment]
之前有人提过一个相关pr，合并进去了但没发布，现在已经发布最新的2.0.9  
以下是配置中新增的部分，不需要那个中间件把'web'去掉就行了
`'middleware_base'       => ['web'], # 插件所有路由的基础中间件`

**Comment by lwhdev** [comment]
谢谢
