### ISSUE TITLE
关于创建目录，提个建议

### ISSUE THREAD

**Issue by HimiHL** [peinhu/AetherUpload-Laravel#12]
按照你的文档，配置过后，能使用，但是当我想将文件存储目录更换时，遇到了两个问题。

1.更换过后，我通过手动创建目录并赋予权限，上传图片时提示：“错误：无法创建文件”，发现是UploadHandler.php 第40行的**mkdir()**函数，没有第三个参数，导致目录无法创建（可能是目录太深了

2.同上情况，发现目录下的_head文件夹也没有自动生成，然后在 Receiver.php 中的 getUploadHeadPath() 方法中添加了一个判断目录是否存在并创建目录的代码。

我不知道这个是不是专门拿来提建议的，还是拿来解决问题的，如果有错还望给个更好的办法，新手。。  -.-

**Comment by peinhu** [comment]
@cxzfb   
你好，在不了整个插件运行逻辑和原理的情况下，不建议自行修改，否则如果自己忘记改了哪些的话，后面我给你建议时可能会出现奇怪的问题导致无法运行。  
从你的描述中似乎没有提到更换目录具体做了哪些改动，所以我只能猜测可能的原因，请注意目录的设置只支持分组目录-子目录的结构，不支持子目录再往下细分。另外在example页面的源代码里有一个JS初始化的函数，其中的参数是配置分组的名字，默认是file，如果你设置了分组，那么这边也要修改成你分组的命名。

**Comment by HimiHL** [comment]
我在配置中仅修改了文件上传存储的路径(第一行配置)，没有对分组进行调整修改。

具体修改是第1个问题中40行的mkdir补上了第三个参数。

**Comment by HimiHL** [comment]
我还是详说吧，

我将config中的 “UPLOAD_PATH” 从storage/app/aetherupload 修改成 storage/app/public/uploads (懒得写PHP了，直接说的目录)，然后我手动mk了这个“uploads”目录。接着问题就出来了。

上传文件时，提示“错误：无法创建文件”，经过查看源码，是因为 Receiver.php 中


        if ( ! (@touch($this->uploadPartialFile) && @touch($this->uploadHead)) )
        {
            return Responser::reportError('无法创建文件');
        }

`
报了错误，然后经过调试，并没有在`uploads`目录下创建“file”（也就是config中的分组名），然后在 UploadHandler.php 中，发现一个mkdir()的代码，可能是因为目录太深，导致无法创建成功。于是将原本的 `@mkdir($uploadFileSubFolderPath, 0755);` 改成了 `@mkdir($uploadFileSubFolderPath, 0755,true);` 后，目录可以创建了。

紧接着，还是报了这个错误，一样的看了调试过后，还是那一行报的错误，然后检查了下，没有发现什么地方有创建 `_head` 文件夹，于是在 `Receive.php` 中的 `getUploadHeadPath()` 中添加了下列代码：


        $path = $this->config->get('UPLOAD_PATH') . DIRECTORY_SEPARATOR . $this->config->get('HEAD_DIR');
        if( !is_dir($path)){
            @mkdir($path,0755,true);
        }

问题就解决了。

**Comment by peinhu** [comment]
@cxzfb   
修改了上传目录本地物理路径的话，应该在新的上传目录路径下手动创建_head目录和分组目录，并赋予755权限，这样就没问题了。  
至于你说的mkdir的改动我之前也考虑加第三个参数，这样更换分组以后可以自动创建目录比较方便，但是我发现这样过分信任客户端提交的参数会带来安全隐患。mkdir的第三个参数是递归创建文件夹，不但会自动创建子目录的文件夹，还会自动创建分组目录的文件夹，如果客户端的分组名参数被人为修改，比如改为一个不在你配置中的分组命名，那么你的服务器上就多出了一个额外目录，如果它不停的修改初始化时的分组名参数，那么你的上传主目录文件夹下会出现无数个分组目录。而且这个分组不在你配置中，那么也就不会受到你配置中的大小和类型限制，总之会带来比较多的问题，手动创建一次也不麻烦，不建议加那个参数让它自动创建。

**Comment by HimiHL** [comment]
好，那我就手动创建，谢谢。
