### ISSUE TITLE
上传的时候提示 aetherupload/init 这个路由找不到

### ISSUE THREAD

**Issue by wdgwgz** [peinhu/AetherUpload-Laravel#13]
上传的时候提示 aetherupload/init 这个路由找不到，
在 route 里面好像也没有 aetherupload/init 这个路由，只有 aetherupload/initialize

**Comment by peinhu** [comment]
@wdgwgz 路由名字发生过更换，但我看了下最近的release没这个问题，是不是你安装过以前的版本，那样的话需要重新执行一次`php artisan vendor:publish --tag=aetherupload --force`，出现这个问题应该是因为你的js文件是旧版的。

**Comment by wdgwgz** [comment]
之前 laravel5.3 的时候 一直在用 dev-master，最近升级到 5.4 发现的这个问题。
现在我更新到 "peinhu/aetherupload-laravel": "~1.0" 
路由没有问题了。
但是选择文件后不自动触发上传，实例也是这样。

**Comment by peinhu** [comment]
@wdgwgz 我刚又新建项目试了下没这个问题，laravel版本5.4.23，不自动触发上传应该是aetherupload.js文件或example.blade.php里的问题，你先自己排查一下，应该是旧版文件和新版不对应造成的。

**Comment by wdgwgz** [comment]
OK， 已解决。
老模板缺少 onchange="AetherUpload.upload('file')"
