### ISSUE TITLE
请问如何获得上传文件的mime-type

### ISSUE THREAD

**Issue by orinchen** [peinhu/AetherUpload-Laravel#15]

**Comment by peinhu** [comment]
可通过“上传完成前事件”或“上传完成事件”获得，参考laravel的事件系统，通过事件监听器可访问receiver的实例，进而获得receiver的属性uploadPartialFile，有了文件路径就可以调用函数获取mime-type了。

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
现集中关闭已解决问题，如仍有疑问请跟帖留言。
