### ISSUE TITLE
问一下这个如何支持一次上传多个文件?

### ISSUE THREAD

**Issue by hanxianglu** [peinhu/AetherUpload-Laravel#17]

**Comment by peinhu** [comment]
目前只支持单个文件上传。

**Comment by peinhu** [comment]
@hanxianglu 大文件一般都是一次传一个的吧，一次要传多个，请问什么场景下有这个需求呢？

**Comment by hanxianglu** [comment]
例如我现在3个视频同时对应一个项目，如果同事上传成功了才保存这个项目

**Comment by peinhu** [comment]
@hanxianglu 目前的话可以采用一个临时方法达到目的，上传完成后会禁用file组件，并回调一个js的success方法，可以在那个方法里面给你的表单增加input，把文件保存的路由赋值给它，记得每次需要上传前解除file组件的禁用。

**Comment by hanxianglu** [comment]
逻辑上会有点问题，不过我试试能不能避免，感谢

**Comment by peinhu** [comment]
@hanxianglu   
应该没问题，我已经试验成功了，在success方法中判断如果不是最后一个上传完成的文件，就使用`$('#aetherupload-file').removeAttr('disabled');`解除禁用。  
我再看看这种需求多不多，多的话后续版本考虑加入文件批量上传的支持。

**Comment by luoyangpeng** [comment]
不一定要上传大文件呀

**Comment by peinhu** [comment]
@luoyangpeng 这个就是专门用来传大文件的，小文件一般直接传就行了，用不着这个。

**Comment by peinhu** [comment]
@hanxianglu 最新发布的v1.0.6已经支持“同一界面多个控件”，考虑到通用性和复杂性，批量上传功能暂不支持，敬请谅解。
