### ISSUE TITLE
删除创建的文件夹后，不能创建

### ISSUE THREAD

**Issue by luoyangpeng** [peinhu/AetherUpload-Laravel#19]
删除创建的文件夹后，不能创建。提示无法创建文件

**Comment by peinhu** [comment]
最新版1.0.5可以用artisan自动创建，之前的版本需要手动创建，并赋予文件夹755权限。

**Comment by peinhu** [comment]
@luoyangpeng 不知道回答有没有解决你的问题，issue我先关闭了，有疑问继续提出。
