### ISSUE TITLE
php artisan 错误如何处理

### ISSUE THREAD

**Issue by wwwwwwwwwwww** [peinhu/AetherUpload-Laravel#20]
laravel 版本5.2
2 执行php artisan aetherupload:publish来发布一些文件和目录
用的是php artisan vendor:publish
------------------------------------------------------------------------------------------------
分组配置：在配置文件的GROUPS下新增分组，运行php artisan aetherupload:groups自动创建对应目录。
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "aetherupload" namespace.

**Comment by peinhu** [comment]
只有最新的1.0.5版才能使用aetherupload:groups这个命令，之前的版本需要手动创建对应目录，并赋予文件夹755权限。

**Comment by peinhu** [comment]
@wwwwwwwwwwww 我使用laravel 5.2.31试过了，无法重现这个错误，请确认安装的是1.0.5版本，才可以使用那个命令。issue我先关闭了，有疑问继续提出。
