### ISSUE TITLE
請問如何進行多檔案同時上傳？

### ISSUE THREAD

**Issue by zhouz1830** [peinhu/AetherUpload-Laravel#21]
請問AetherUpload能做多文件同時上傳嗎？ 多實例的意思。如果可以，請問大概要如何操作？

**Comment by peinhu** [comment]
这个是同步上传的，不是异步，无法同时传输多个文件，就算有多个文件也是一个一个上传的，最新的1.0.6版本支持多文件上传，但是要相应的增加表单控件，比如有6个文件就要有6个表单控件，具体见示例文件。
