### ISSUE TITLE
上传文件一直返回一个很久之前的旧文件地址

### ISSUE THREAD

**Issue by luoyangpeng** [peinhu/AetherUpload-Laravel#22]
/201709/8c73b5cc9d00291507d309355829014b.xlsx for reading! File does not exist.
这个目录已经删除，改成固定的文件夹了。但是上传后返回的是这么个地址？
还有配置文件使用date 时区没有定义的问题

**Comment by peinhu** [comment]
你是不是安装了redis启用了秒传功能？在readme中已经提示了，如果启用秒传功能的话，删除文件的同时也需要删除redis中对应的hash记录（调用RedisHandler中的deleteOneHash方法），否则会产生脏数据。如果已经产生脏数据了，可以使用artisan命令aetherupload:build重建redis中的hash清单。
配置文件中使用了date函数，时区可以在laravel的app.php配置文件中设置。
