### ISSUE TITLE
更换上传目录UPLOAD_PATH问题

### ISSUE THREAD

**Issue by andyliuliming** [peinhu/AetherUpload-Laravel#23]
指定了/data/xxx 目录，但是上传的文件还是放到了storage/app/blabla下面去。

**Comment by andyliuliming** [comment]
@peinhu

**Comment by andyliuliming** [comment]
看起来是每次的publish去覆盖了修改过的文件。

**Comment by peinhu** [comment]
@andyliuliming 你好，我用v1.0.7试过了没有问题。注意目录UPLOAD_PATH应该是绝对路径，而且此目录下应该需要有_head和file(如果使用默认分组的话)这两个文件夹。

**Comment by andyliuliming** [comment]
现在更奇怪了，上传了之后好像文件名字能拿到，但是那个文件夹下面看不到内容。

<?php

return [
    "ENABLE_EXAMPLE_PAGE" => true, # 启用示例页面，访问域名/aetherupload，生产环境下请将该选项设置为false
    "CHUNK_SIZE"          => 1 * 1000 * 1000, # 上传时的分块大小（B），默认为1M，越大传输越快，需要小于web服务器和php.ini中设置的上传限值
    "UPLOAD_PATH"         => storage_path() . DIRECTORY_SEPARATOR . "app" . DIRECTORY_SEPARATOR . "aetherupload", # 上传目录的本地物理路径
    #"UPLOAD_PATH"         => "/data/aetherupload",
    "HEAD_DIR"            => "_head", # 指针头文件目录的名称，建议保持默认
    "FILE_SUB_DIR"        => @date("Ym", time()), #资源文件目录的子目录生成规则，变量或常量均可
    "REDIS_KEY"           => "aetherupload_file_hashes", #redis中hashes的key名称
    "GROUPS"              => [ # 分组，可设置多个不同分组，各自拥有独立配置
        "file" => [ # 新增分组请尽量使用video、audio等有意义的分组名
            "FILE_MAXSIZE"                 => 0, # 被允许的资源文件大小（MB），0为不限制
            "FILE_EXTENSIONS"              => "zip,jpg,jpeg,png,zipr", # 被允许的资源文件扩展名，空为不限制，多个值以逗号分隔
            "MIDDLEWARE_PREPROCESS"        => [], # 上传预处理时的路由中间件
            "MIDDLEWARE_SAVE_CHUNK"        => [], # 上传文件分块时的路由中间件
            "MIDDLEWARE_DISPLAY"           => [], # 文件展示时的路由中间件
            "MIDDLEWARE_DOWNLOAD"          => [], # 文件下载时的路由中间件
            "EVENT_BEFORE_UPLOAD_COMPLETE" => '', # 上传完成前触发的事件（临时文件），Receiver的实例被注入
            "EVENT_UPLOAD_COMPLETE"        => '', # 上传完成后触发的事件（已存文件），Receiver的实例被注入
        ],

    ],
];

**Comment by andyliuliming** [comment]
我看到publish那个任务会把那个config文件覆盖。
执行的顺序应该是怎样？

**Comment by peinhu** [comment]
@andyliuliming UPLOAD_PATH那一项你改成了'/data/aetherupload'这个是吗，那你需要在'/data/aetherupload'下创建_head和file目录。如果还不行，你重新执行一次php artisan aetherupload:publish，把设置都初始化成默认的，然后不要改默认的设置直接用示例，如果默认设置下没问题的话，就是你修改目录造成的问题。

**Comment by peinhu** [comment]
@andyliuliming 如果文件名字能拿到的话，那就是上传成功了，你是不是看错目录了？'/data/aetherupload'这个目录表示绝对路径，是不在项目文件夹里的。

**Comment by syyzw1985** [comment]
@peinhu  我也遇到类似的问题，我只是吧UPLOAD_PATH修改成storage_path()."/public 就提示创建文件失败,很想知道原因。我是windows机器，所以不存在权限的问题。

**Comment by peinhu** [comment]
@syyzw1985 首先storage_path()."/public"这个目录必须是要存在的，另外此目录下必须有file和_head两个目录。

**Comment by syyzw1985** [comment]
@peinhu 感谢，感谢，已经解决了，万分感谢！

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
现集中关闭已解决问题，如仍有疑问请跟帖留言。
