### ISSUE TITLE
Pause and Cancel upload

### ISSUE THREAD

**Issue by dels07** [peinhu/AetherUpload-Laravel#24]
Pardon me because I don't speak chinese, I want to ask if this package support for pause/resume and canceling upload?

Also whether it possible to upload file directly to Minio (or other Storage::disk) without the need of using temp folder in app/storage?

Thanks

**Comment by peinhu** [comment]
@dels07   
This package does not support pause/resume/canceling upload, though it is able to support the features however i don't think it's necessary to do that.  
And this package only support the local storage for now, but if the storage service provider support the 'append' operation, then it is possible to upload files directly without temp folder(TO DO).

**Comment by dels07** [comment]
@peinhu 
Currently I working with large video upload project (1-5 Gb), so it's better if user can cancel if they choose wrong video. Also is it possible to use "upload" button instead of automatically upload after choosing file?

**Comment by peinhu** [comment]
@dels07 
To cancel the upload:  
Add this function to AetherUpload object in aetherupload.js and call it
`    cancel: function(){
        clearInterval(this.uploadChunkInterval);
    },`  
  
To use "upload" button:  
In the view file, remove "onchange=..." on the file dom, and give an id to the file dom, then add the code below to the button
`onclick="aetherupload(document.getElementById(the-id-of-the-file-dom),'file').upload()"`

**Comment by peinhu** [comment]
I consider this issue is solved, if you still have questions please reopen this issue and append.
