### ISSUE TITLE
如何关闭秒传功能

### ISSUE THREAD

**Issue by minsy93** [peinhu/AetherUpload-Laravel#26]

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
秒传开关已成为配置项。现集中关闭已解决问题，如仍有疑问请跟帖留言。
