### ISSUE TITLE
用的laravel  ftp来存储

### ISSUE THREAD

**Issue by rainforyou** [peinhu/AetherUpload-Laravel#27]
能不能上传？不是存在本地，视频存储和web分离的，能用这个吗

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
尝试过ftp储存，发现传输效率低还有内存问题，原因不明，另外ftp无法实现秒传功能的计算文件md5哈希值流程，故无法支持ftp。现集中关闭已解决问题，如仍有疑问请跟帖留言。
