### ISSUE TITLE
自定义上传路径, 比如日期格式

### ISSUE THREAD

**Issue by diguojin** [peinhu/AetherUpload-Laravel#3]
请问, 在现有的方案下如何做到, 根据上传文件的时间自动创建文件夹?

比如: 今天是 2017年1月12日 , 我上传了文件, 之后格式为
`/home/app/storage/app/uploads/aetherupload_file/20170112/*.jpg`

**Comment by diguojin** [comment]
我在想 , 是否可以在 Uploader.php 65行之后加入 
```
        $fileFullPath = self::$UPLOAD_PATH . self::$UPLOAD_FILE_DIR;
        if(!file_exists($fileFullPath)){
            mkdir($fileFullPath, 0777, true);
        }
```

**Comment by diguojin** [comment]
然后配置文件 

```
return [
......

    "UPLOAD_PATH" => storage_path() . DIRECTORY_SEPARATOR . "app" . DIRECTORY_SEPARATOR . "uploads",
    # 上传目录的本地物理路径

    "UPLOAD_FILE_DIR" => DIRECTORY_SEPARATOR . "aetherupload_file" . DIRECTORY_SEPARATOR . date('Ymd', time()),

......

];
```

**Comment by peinhu** [comment]
@diguojin   
你好，我仔细看了一下原文件，临时的话可以这么改，建议mkdir函数写成`mkdir($fileFullPath, 0755)`，file_exists函数用is_dir替代可提升效率。  
但是只修改这边的话，会影响到cleanUpDir这个函数，而且会使接近0点时上传的大文件产生错误，具体的修改会在之后几个提交中加入。

**Comment by diguojin** [comment]
感谢答复, 仔细一想 确实有点问题.  我在考虑下, 如果有好的解决办法, 我会贴出来

**Comment by peinhu** [comment]
分组配置和子目录功能已在v1.0.2中加入，这个问题应该是解决了。
