### ISSUE TITLE
请问在文件哈希时 500 Internal Server Error错误是什么原因呢

### ISSUE THREAD

**Issue by 1191544503** [peinhu/AetherUpload-Laravel#31]

**Comment by peinhu** [comment]
@1191544503  这个问题之前没人提出过，我也没遇到过。“文件哈希时”具体是哪个请求的时候？在预处理请求（preprocess）之前前端会尝试哈希一次文件，在最后一个上传请求（uploading）时后端也会哈希一次文件，所以不明白到底问题指的是哪次请求？能否详细描述一下操作过程和遇到的情况。

**Comment by 1191544503** [comment]
可能不是哈希的时候，就是再用ajax请求preproces的时候，因为我的项目没在根目录下，如果我直接用demo的话Ajax请求会404，然后我将Ajax请求url前面的/去掉，然后发生500错误

**Comment by peinhu** [comment]
@1191544503 laravel一般都是需要把web入口设置在public目录的，而不是其他上级目录，否则很可能会造成问题，这点跟有的其他框架不太一样。

**Comment by 1191544503** [comment]
3Q我试一下

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
现集中关闭已解决问题，如仍有疑问请跟帖留言。
