### ISSUE TITLE
如何解决很多分组问题？

### ISSUE THREAD

**Issue by liziliang123** [peinhu/AetherUpload-Laravel#32]
比如用户需要将文件上传到自己的文件目录下，不同的目录，分组也不一样，分组太多无法每个都定义，此时上传配置是无效的，有什么方法可以解决这个问题？

**Comment by peinhu** [comment]
@liziliang123 用户数和每个用户上传的东西不多的话，可以把子目录生成规则（FILE_SUB_DIR）改成按照具体某个用户名或用户id，如` "FILE_SUB_DIR"        => session('user_id'),`，类似这种，理论上这样是可行的，你试下。

**Comment by liziliang123** [comment]
考虑过目录规则这个方法，

**Comment by liziliang123** [comment]
aetherupload.php中的"GROUPS" 与aetherupload($("#file"),"GROUPS").success(someCallback).upload()的分组名称对应，正常这两个分组名称需要一样，可不可以将前者的名称只需要匹配后者的名称结尾就有效，比如说正常是group=group才有效，可不可以改成group=parent/group这种匹配形式也有效？

**Comment by peinhu** [comment]
@liziliang123  可以的吧，你用js把后者的值截取一下就行了，比如`aetherupload($("#file"),某截取方法('parent/group'))`，或者你在aetherupload这个方法里截取也可以，需要改一下aetherupload.js

**Comment by peinhu** [comment]
@liziliang123 我感觉你想表达的意思好像跟描述的不太一样，猜你是把文件目录给改成user/group/subdir/这种形式了？

**Comment by liziliang123** [comment]
是的，文件目录给改成user/group/subdir/这种形式，user是不断变化的，通过目录规则那个方法可以达到这个效果，但是不适应使用session。现在想达到只要匹配group这个字段,group前面的路径不管怎么变化配置都有效

**Comment by peinhu** [comment]
@liziliang123 能问下为什么用户上传的文件一定要放在他自己的文件夹里吗？一般来说没有这个需求，数据库能查到路径就行了。

**Comment by peinhu** [comment]
@liziliang123 一定要这样的话倒是有个办法  
1 把user加在配置的UPLOAD_PATH最后，如`"UPLOAD_PATH"         => storage_path() . DIRECTORY_SEPARATOR . "app" . DIRECTORY_SEPARATOR . "aetherupload".DIRECTORY_SEPARATOR.session('user_id'),`  
2 然后把UploadHandler.php中的55行加个参数改成`@mkdir($uploadFileSubFolderPath, 0755 ,true);`  
3 再把Receiver.php中的85行改成`return dirname(ConfigMapper::get('UPLOAD_PATH')) . DIRECTORY_SEPARATOR . ConfigMapper::get('HEAD_DIR') . DIRECTORY_SEPARATOR . $this->uploadBaseName . '.head';`  
这样就可以了

**Comment by liziliang123** [comment]
强迫症，项目很不错，谢谢了。
