### ISSUE TITLE
不同分组下的秒传问题

### ISSUE THREAD

**Issue by liziliang123** [peinhu/AetherUpload-Laravel#33]
例如有两个分组：img与video , 首先向img中传入a.txt , 返回的savePath是img , 当再次向video传入一样的a.txt ,直接秒传了，返回的savePath还是img ,如何解决这个问题？

**Comment by peinhu** [comment]
@liziliang123 个人认为这个不属于问题，秒传本身就是基于文件哈希值的，与分组无关，img和video分组本应该包含的是两种类型的资源，不应该拥有相同的文件。不过即使像你这么操作，返回的文件属于其他分组，也是不影响使用的，还是能正常访问到那个文件。

**Comment by liziliang123** [comment]
img与video只是举例，也可以是同类型的分组，分组就是为了区分上传的一些权限，比如说文件大小，但总会出现不同分组的用户上传相同文件的问题。如果一个分组只允许上传1M大小的文件，却突然出现1GB的文件，这不是很合理吧？

**Comment by peinhu** [comment]
@liziliang123 如果是包含同类型文件的分组，那么确实会出现你说的问题。

**Comment by peinhu** [comment]
@liziliang123 这种情况目前没想到什么好的解决办法，我的建议是最好不要把分组和用户权限挂钩，如果要控制访问权限，那就交给专门的权限控制系统，如果你有什么好的方法也欢迎提出来：）

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
问题已修复，感谢提出，目前只有同分组的相同文件才会走秒传流程，相同文件上传不同分组不会秒传。现集中关闭已解决问题，如仍有疑问请跟帖留言。
