### ISSUE TITLE
今天发现个问题...

### ISSUE THREAD

**Issue by sheghai** [peinhu/AetherUpload-Laravel#34]
服务器及环境：centos-7.4.1708+php7.2+Nginx。吓上传后结果如下：
执行回调 - 文件原名：store_0709114622.apk | 文件大小：8.34MB | 文件储存名：1b85c078d04bff0189f428bd39bf5e9c.apk

在本地上传（phpStudy集成环境）如下：
执行回调 - 文件原名：store_0709114622.apk | 文件大小：8.34MB | 文件储存名：apk\201807\1b85c078d04bff0189f428bd39bf5e9c.apk

居然**文件储存名**不对

返回路径不能把UPLOAD_PATH一起返回吗？

**Comment by peinhu** [comment]
@sheghai 确定服务器和本地用的版本是一样吗？估计你服务器用的是早期版本，还不支持分组和子目录，这两个是后来加入的。

**Comment by peinhu** [comment]
@sheghai 也有可能都已经是支持分组和子目录的，但是你用的两个版本稍微有些差异，在示例页面显示的内容稍有不同，最后的结果还是应该以示例页面点击提交后的内容为准，那边的内容是可以储存到数据库里的内容，要访问已上传资源的话直接拼出url就行了。
