### ISSUE TITLE
中间件验证用户登录

### ISSUE THREAD

**Issue by HeartOfZealot** [peinhu/AetherUpload-Laravel#35]
你好，我在配置文件中加入了验证用户是否登录的中间件

发现打印 \Auth::user() 输出为null

然后在 UploadHandler 的 preprocess 和 saveChunk 中打印用户变量仍为null

所以，我无法验证调用该接口时，用户是否已经登录

查看了一下，cookie中laravel_session是和页面用的同一个

请问怎样解决呢，谢谢

**Comment by peinhu** [comment]
@HeartOfZealot 你好，根据laravel的设计，需要使用session的话，必须有相应的session中间件(如web中间件)。  
如果你是在自定义的页面测试的话，将配置文件的相应中间件(如MIDDLEWARE_PREPROCESS)设置为`['web','my_middleware']`，注意web一定要在你的中间件**前面**。  
如果你是在自带示例页面测试的话，除了上述的操作，另外还需要在routes.php中为`aetherupload`这个路由加上web中间件，即改成：
```php
    Route::get('aetherupload', function () {
        return view('aetherupload::example');
    })->middleware('web');
```  
这个是我的疏忽导致的，下个版本会修正这个小问题，感谢提交🙏。

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
此问题已修复。现集中关闭已解决问题，如仍有疑问请跟帖留言。
