### ISSUE TITLE
上传到服务器后路由地址报404错误

### ISSUE THREAD

**Issue by yujiak** [peinhu/AetherUpload-Laravel#37]
本地测试能正常上传文件，git到服务器上后路由就出问题了，请问这个是怎么回事呢？自带的示例页面也打不开，本地是能打开的

**Comment by peinhu** [comment]
@yujiak git提交会忽略某些文件的，请把本地项目文件打包上传再解压，如果还是有这个问题，那才能归因于代码bug。
另外，请确保服务器上相关文件和目录有正确的权限。

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
现集中关闭已解决问题，如仍有疑问请跟帖留言。
