### ISSUE TITLE
如何 使用oss 作为上传目录

### ISSUE THREAD

**Issue by ooxill** [peinhu/AetherUpload-Laravel#38]
我服务器 文件系统 是集成的阿里云oss  laravel 用的 acobcyl/ali-oss-storage集成包
但是如果用这个上传 文件又回到了本地
上传目录 我看只能是 本地的绝对路径

**Comment by peinhu** [comment]
@ooxill 目前不支持oss，如果用第三方oss储存那直接用它们家的sdk就行了，一般都有大文件上传的接口的。

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
现集中关闭已解决问题，如仍有疑问请跟帖留言。
