### ISSUE TITLE
不能再次选择吗？

### ISSUE THREAD

**Issue by SmileCandice** [peinhu/AetherUpload-Laravel#39]
只能上传一次呢

**Comment by SmileCandice** [comment]
@peinhu

**Comment by peinhu** [comment]
@SmileCandice 按照目前设计的上传逻辑，还不支持单组件多文件上传，但支持多组件多文件上传，如果要上传多个文件，像示例中那样增加表单上传组件的个数就行。

**Comment by peinhu** [comment]
@SmileCandice 根据你的需求，稍微写点js让表单上传组件做到自动新增应该就可以了。

**Comment by SmileCandice** [comment]
@peinhu 好的呢，我的意思不是想上传多个，就是上传之后不能再改了现在是对吧，如果我想修改呀，不是新增呢

**Comment by peinhu** [comment]
@SmileCandice 
目前要修改的话，一是直接重新加载整个表单页面，比较粗暴；二是稍微写点js将id为file的那个文件input解除disabled属性，并且最好清空id为savedpath的隐藏input，不清空应该也可以你试一下。
这个问题有待改进，感谢提交。

**Comment by SmileCandice** [comment]
好的呢，那我是获取到文件名之后给她解除disabled嘛

**Comment by peinhu** [comment]
@SmileCandice 取到对应上传组件里id为file的那个就行了，然后解除disabled。

**Comment by SmileCandice** [comment]
好的呢，可以了，谢谢你啦，现在可以再次点击了

**Comment by SmileCandice** [comment]
@peinhu 我想再问下有没有值可以区分“未选择文件“和“未上传完成“这两种状态呢

**Comment by peinhu** [comment]
@SmileCandice 目前有文字状态提示但没有值，不过你可以自己维护一个。比如初始状态是'未选择'，然后在一个button上绑定自己的方法来触发上传文件，同时修改状态为'上传中'，最后通过上传完成的回调方法来修改状态为'已上传'。

**Comment by peinhu** [comment]
@SmileCandice 能问一下为什么需要数值来区分这两种状态吗？是出于什么需求呢？

**Comment by SmileCandice** [comment]
嗷嗷好的呢知道了，没什么特别的需求，就是当修改的时候，是可以不传文件的，我区分不了是没选择还是没完成嘛，然后需求就是没选择可以提交，没完成不可以

**Comment by peinhu** [comment]
@SmileCandice 修改的时候你先把原来的清空，就是刚才我说的id为savedpath的隐藏input，应该就没这个问题了，因为只有上传完成了savedpath才会有值。

**Comment by SmileCandice** [comment]
是呀，但是savedpath没值一个是没选择文件一个是没上传完成嘛，就是要区分呀，我先弄个按钮的

**Comment by SmileCandice** [comment]
@peinhu嗯呢，我在aetherupload方法里改变按钮状态就好了呢，谢谢你这么有耐心

**Comment by peinhu** [comment]
@SmileCandice
修改的时候是不能不传文件的，要么全部清空，类似重置，要么强制重新选择上传，如果解锁了不重新传，提交表单的时候原文件会被不分片整个提交！

**Comment by SmileCandice** [comment]
我没理解你的意思哎，什么情况是解锁了不重传呢？我这个修改意思是（一条记录的一个修改按钮，弹窗显示这条的文件名字，因为不能给inputfile赋值所以显示名字即可，然后名字下方是选择文件按钮，就是可以不点击这个按钮就提交修改请求，这样我们就不会走上传呀，也不会提交文件）

**Comment by SmileCandice** [comment]
@peinhu 我觉得不会存在说解锁了不重传这种情况的吧，我也不清楚这种情况是怎么样子啊

**Comment by peinhu** [comment]
@SmileCandice
那是我理解错了，我以为你是要在上传完成后换一个文件这种修改，问题解决了就好。

**Comment by SmileCandice** [comment]
@peinhu 这种再次选择也有的，这种有什么风险吗，换个文件如果没上传完成就提示没上传完成，如果取消了那么还在上传着，如果他强制刷新页面了我也弄不了啊

**Comment by SmileCandice** [comment]
你的意思是再次选择的时候没选择文件，那么会把原来的已经选择的文件整个不分片提交吗？

**Comment by peinhu** [comment]
@SmileCandice
对，就是这个风险，提交表单时必须保证file是disabled状态。

**Comment by SmileCandice** [comment]
额，那这确实是个问题，而且我还不能强制他重新选择一定要选文件的呀，把他原来选的清空了也不合理呀，

**Comment by peinhu** [comment]
@SmileCandice 看你inputfile有没有加name属性，加了就有这个风险，没加就没问题不会提交，只是提醒一下，有的人会习惯性给input加上name属性。

**Comment by SmileCandice** [comment]
@peinhu 额加了的，我就是有的人一员，那我去掉的，康萨米达

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
现集中关闭已解决问题，如仍有疑问请跟帖留言。
