### ISSUE TITLE
不能再次选择吗？

### ISSUE THREAD

**Issue by SmileCandice** [peinhu/AetherUpload-Laravel#40]
噗，不好意思，怎么不小心删掉了

**Comment by SmileCandice** [comment]
把你的回答贴上：你的意思是按目前逻辑不支持单组件多文件上传，如果要上传多个要增加上传组件的个数

**Comment by SmileCandice** [comment]
@peinhu 我的意思是不想上传多个，就是上传之后想修改文件呀，重新上传，这个修改就是你说的多文件是吗，

**Comment by peinhu** [comment]
你关闭了，没删掉，我重新打开吧，这个关了。
