### ISSUE TITLE
限制文件上传后缀的格式是怎么写的

### ISSUE THREAD

**Issue by 1113961224** [peinhu/AetherUpload-Laravel#41]
我在config 的aetherupload.php里 修改 "RESOURCE_EXTENSIONS"          => [‘.mp4’], # 被允许的资源文件扩展名  传其他的文件格式还是可以上传的

**Comment by peinhu** [comment]
后缀不带点的，你试下对不对。

**Comment by 1113961224** [comment]
嗯，可以了，谢谢

**Comment by 1113961224** [comment]
还有一个问题，就是我想要修改文件上传的路径，上传成功后，文件打开显示空文件，我是在config的filesystems.php里面修改 'local' => [
            'driver' => 'local',
            'root' => public_path('Uploads/video'),
        ],
和 'public' => [
            'driver' => 'local',
              'root' => public_path('Uploads/video'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

**Comment by peinhu** [comment]
> 还有一个问题，就是我想要修改文件上传的路径，上传成功后，文件打开显示空文件，我是在config的filesystems.php里面修改 'local' => [
> 'driver' => 'local',
> 'root' => public_path('Uploads/video'),
> ],
> 和 'public' => [
> 'driver' => 'local',
> 'root' => public_path('Uploads/video'),
> 'url' => env('APP_URL').'/storage',
> 'visibility' => 'public',
> ],

修改`config/aetherupload.php`中“UPLOAD_PATH”对应的内容，记得手动创建相应文件夹。

**Comment by 1113961224** [comment]
这个文件里没有这个参数，需要手动加吗

**Comment by 1113961224** [comment]
我自己加了参数没效果

**Comment by peinhu** [comment]
> 这个文件里没有这个参数，需要手动加吗

我检查了一下，这个参数在v1.0.x(从v1.0.0到最近的v1.0.7)版本都是有的，你用的是什么版本？

**Comment by 1113961224** [comment]
我在composer.json没看到版本号只看到"peinhu/aetherupload-laravel": "dev-master"

**Comment by 1113961224** [comment]
你现在的代码里面好像也没有这个配置项

**Comment by peinhu** [comment]
> 你现在的代码里面好像也没有这个配置项

现在dev-master分支是2.0.0的beta测试版，比起1.0.x加了很多没经过测试、不稳定的功能而且还没正式打包发布，是不能用在生产环境的！你在安装的时候是用`composer require peinhu/aetherupload-laravel ~1.0`这个命令安装的吗？按道理应该不会安装dev-master这个没打包发布的分支才对啊。

**Comment by 1113961224** [comment]
是我命令用错了，我直接装了dev-master,我去重装下，太感谢了

**Comment by peinhu** [comment]
> 你现在的代码里面好像也没有这个配置项

记错，不是beta，是alpha内部测试版，连beta测试都算不上。。。  
请别用这个版本了，非常不稳定，换成v1.0.7版本。

**Comment by 1113961224** [comment]
好的
