### ISSUE TITLE
请问前后端分离的情况下，如何使用这个插件

### ISSUE THREAD

**Issue by arin-guo** [peinhu/AetherUpload-Laravel#42]
我这边前后端分离开发，前端引入了spark-md5.min.js和aetherupload.js这两个文件。
然后前端上传文件的时候申请接口，比如http://192.168.1.2/upload路由
然后在后端控制器里upload方法里写上\AetherUpload\ResourceHandler::getDisplayLink(request()->input('file1'));
发现无法使用，主要是前端有些参数没有取到

**Comment by peinhu** [comment]
@guo14903 后端不需要写相关代码，只要获取你表单中`<input type="hidden" name="file1" id="savedpath" >`这里面你自定义的name值就行了。
