### ISSUE TITLE
建议前端js换个目录

### ISSUE THREAD

**Issue by nickfan** [peinhu/AetherUpload-Laravel#43]
现在publish以后拷贝到前端的目录是public/js/xxx.js
这个在5.5以后默认是忽略的目录，对代码发布测试不友好，建议换为更规范一点的public/vendor/aetherupload/js/xxx.js
的路径，下次git添加以后就不会变了。

**Comment by peinhu** [comment]
@nickfan 感谢提醒🙏，我也发现了这个问题，下一版发布会解决。[链接](https://github.com/peinhu/AetherUpload-Laravel/blob/master/src/AetherUploadServiceProvider.php#L27)
