### ISSUE TITLE
请问如何上传exe的文件呢

### ISSUE THREAD

**Issue by JasonZsl6** [peinhu/AetherUpload-Laravel#44]
![image](https://user-images.githubusercontent.com/32836782/50473695-efba1580-09f8-11e9-95c6-299d1cd0e6ce.png)
我在源码中发现了这个方法，我在配置文件中设置FILE_EXTENSIONS => "exe" 也没有用，反正就是想上传exe后缀的文件

**Comment by peinhu** [comment]
@JasonZsl6 后缀名过滤采用的是黑名单+白名单的方式，你上面提到的那些就是黑名单上一定会被过滤的后缀名，如果你必须要上传这种文件，那只能把黑名单中相应的后缀去掉。如果确实有这种需求，下一版中考虑把黑名单做成可配置项。

**Comment by JasonZsl6** [comment]
> @JasonZsl6 后缀名过滤采用的是黑名单+白名单的方式，你上面提到的那些就是黑名单上一定会被过滤的后缀名，如果你必须要上传这种文件，那只能把黑名单中相应的后缀去掉。如果确实有这种需求，下一版中考虑把黑名单做成可配置项。

嗯，希望能加上，麻烦咯

**Comment by JasonZsl6** [comment]
> @ JasonZsl6后缀名过滤采用的是黑名单+白名单的方式，你上面提到的那些就是黑名单上一定会被过滤的后缀名，如果你必须要上传这种文件，那只能把黑名单中相应的后缀去掉。如果确实有这种需求，下一版中考虑把黑名单做成可配置项。

向你请教个问题，上传文件过后，生成的文件名是对文件进行hash过后的值吗

**Comment by peinhu** [comment]
@JasonZsl6 是的。

**Comment by peinhu** [comment]
AetherUpload 2 已发布，根据用户反馈和需求，添加分布式部署支持、添加Mime-Type检查、添加头文件redis储存驱动、添加跨域中间件、添加秒传开关配置项、添加自定义黑名单配置项、代码重构优化。  
黑名单已成为可配置项。现集中关闭已解决问题，如仍有疑问请跟帖留言。
