### ISSUE TITLE
兼容php5.6？

### ISSUE THREAD

**Issue by wu-classmate** [peinhu/AetherUpload-Laravel#48]
vendor/peinhu/aetherupload-laravel/src/MimeType.php:825

三元运算符：??

**Comment by peinhu** [comment]
@dajihao 这文件是我从laravel最新版拷贝下来的，我看了下调用的search方法只使用了`$mimes`这个静态变量，没有调用其他带`??`运算符的方法，你那边上传时报错了吗？

**Comment by wu-classmate** [comment]
是的
报错信息：local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '?''

**Comment by peinhu** [comment]
@dajihao 好的感谢提出问题，下个版本修正，你那边把`getMimeTypeFromExtension`方法删掉应该就不会报错了。
