### ISSUE TITLE
怎么用来封装视频上传接口，希望指导一下，谢谢

### ISSUE THREAD

**Issue by FuWenMing** [peinhu/AetherUpload-Laravel#49]

**Comment by peinhu** [comment]
如果是网页的话，按照example文件中的注释引入文件，可以直接上传，不用写后端代码，上传过程已经被扩展包全自动接管了。  
如果你说是API接口，这个我没在app上试过，原理是前端要先发起一个preprocess预处理http请求，参数包含resource_name、resource_size、resource_hash、group和locale。收到返回后，再发起uploading请求开始上传分块，参数包含chunk_total、chunk_index、resource_temp_basename、resource_ext、resource_chunk、group_subdir、resource_hash、group和locale，当返回值中savedPath不为空的时候，就代表上传完成，具体可参照`src/UploadController.php`。

**Comment by peinhu** [comment]
issue先关闭了，如有疑问继续提出。
