### ISSUE TITLE
请问您这个项目在上传的时候是如何判断重复的

### ISSUE THREAD

**Issue by XBisATrouble** [peinhu/AetherUpload-Laravel#50]
秒传功能里计算hash的根据是什么？出现错误碰撞的概率有多大？

**Comment by peinhu** [comment]
计算用的是md5_file函数，看[这里](https://github.com/peinhu/AetherUpload-Laravel/blob/master/src/PartialResource.php#L129) 。  
对于根据文件计算的散列值来说，正常情况下自然碰撞的概率可以忽略不计，因为不可能以测试碰撞的那种频率和数据量来上传文件。但是人为构造两个散列值一样的文件是有可能的，不过问题也不大，这种强行构造出来的文件一般没什么意义，不是正常文件。

**Comment by peinhu** [comment]
如果实在害怕碰撞，可以在hash以外再加入文件大小数值，这样即使发生碰撞，文件大小数值一样的概率也是很低的，总体两个文件的(hash+文件大小数值)相同的概率就更低了。
