### ISSUE TITLE
路由找不到问题

### ISSUE THREAD

**Issue by ximengyi** [peinhu/AetherUpload-Laravel#55]
composer 安装完这个包后，我在routes目录下，无论是web.php，还是api新定义的路由，框架都找不到控制器和方法，会抛出notfoundexception异常， 一开始不知道是哪里出了问题，后来用composer 把这个包卸载了，框架就立马找到控制器了，代码就运行正常了，重复安装几次都能复现这个问题，我的环境是laravel5.7，希望作者告知原因。

**Comment by peinhu** [comment]
1可能是你把路由缓存了，先清除一下缓存试试。
2安装完以后要执行publish命令发布文件

发自我的 iPhone
