### ISSUE TITLE
上传8G超大文件的时候报删除错误，返回404

### ISSUE THREAD

**Issue by tiayo** [peinhu/AetherUpload-Laravel#58]
上传8G的大文件，完成后，最后一个xhr请求状态码为404，日志显示PartialResource.php文件59行报的错：删除失败

**Comment by peinhu** [comment]
是不是当中有断网或者网络不通畅引发断线续传过？

**Comment by peinhu** [comment]
你的服务器系统是32位的还是64位的？

**Comment by peinhu** [comment]
@tiayo

**Comment by tiayo** [comment]
服务器ubuntu18.04 64位的，传输总共有8100多个链接，没注意到有断线重连过

**Comment by peinhu** [comment]
刚才用最新的v2.0.6版测试上传了一个4.61G的文件，中间多次主动断网后再连接触发断线续传，没发现你描述的情况，无法复现问题。
正常上传过程中PartialResource对应的文件是不会被删除的，除非发生了错误，推断是最后一个分块上传完成后的处理过程中已经出了问题，触发了错误处理流程。

**Comment by tiayo** [comment]
发现文件实际是上传成功的，已经在上传目录里了。但是多次传输均出现该问题。4g多的iso文件上传也没问题，就是一个8g的才这样

**Comment by peinhu** [comment]
看一下laravel.log文件中有没有相关报错内容？有的话贴上来。然后试一下几十MB的文件上传会不会出错，排除是文件大小差异的问题。

**Comment by tiayo** [comment]
稍等贴log，文件从小往大的传，除了这个8g的出问题，其他的都没有问题

**Comment by tiayo** [comment]
不好意思刚刚说错了，再检查了一遍发现没有产生laravel的错误日志，进度条提示是上传失败。发现最后一个xhr都是在运行一分钟后，返回404错误。

**Comment by peinhu** [comment]
根据你的描述基本可以确定是上传完成后的处理过程出了问题，只有8G的大文件出问题说明可能和内存有关，有可能处理时内存溢出OOM了。请问一下你用的是最新的v2.0.6版本还是以前的？

**Comment by peinhu** [comment]
@tiayo 实际上传成功的文件它的文件名是类似1559788497790062.iso.part这样的？还是10ca13634070eb8d05dff8d7675ad4f1.iso这样的？安装的扩展是什么版本最好也提供一下。

**Comment by tiayo** [comment]
用的是V2.0.6版本，实际上传成功的是这样的10ca13634070eb8d05dff8d7675ad4f1.iso。环境是php7.2+nginx1.15.8+mysql 5.7.26

**Comment by peinhu** [comment]
好的，这个问题比较诡异，根据你提供的信息，应该至少是直到rename重命名文件那个步骤都是没出错的，那后面其实没多少可能会出错的地方了。
```php
//src/UploadController.php第175行，重命名一个文件，根据你的描述是成功的
$partialResource->rename($completeName = Util::getFileName($resourceRealHash, $resourceExt));

//拼接出保存名称，不太可能出错
$savedPath = SavedPathResolver::encode($group, $groupSubDir, $completeName);

//判断是否配置启用了秒传功能，应该不会出错
if ( ConfigMapper::get('instant_completion') === true ) {
   RedisSavedPath::set($savedPathKey, $savedPath);
}

//删除指针头文件，应该不会出错
unset($partialResource->chunkIndex);

//触发配置的上传完成事件，如果没配置的话不太可能出错
if ( empty($uploadCompleteEvent = ConfigMapper::get('event_upload_complete')) === false ) {
    event(new $uploadCompleteEvent(new Resource($group, ConfigMapper::get('group_dir'), $groupSubDir, $completeName)));
}

//不太可能出错
$result['savedPath'] = $savedPath;
```
等我找个8G的文件来排查吧。

**Comment by tiayo** [comment]
我正在用7g和11g的文件再次测试

**Comment by peinhu** [comment]
好的，你自己也可以排查下问题，主要我现在手边没有8G那么大的文件，得回去后才能测试。

**Comment by tiayo** [comment]
失败了，同样的问题

**Comment by peinhu** [comment]
我把4G的文件复制了一份打包成8G的zip然后上传，成功复现了这个问题。
现在已经解决了，不是代码问题，是执行超时了。文件大的话最后一步计算md5时间就比较长，超过了nginx.conf和php.ini中的相关超时配置中的数值，就会返回'504 Gateway Time-out'错误。
我在nginx.conf中加入设置
```php
send_timeout 300;
fastcgi_connect_timeout 300;
fastcgi_send_timeout 300;
fastcgi_read_timeout 300;
proxy_connect_timeout 300;
proxy_send_timeout 300;
proxy_read_timeout 300;
```
在php.ini中修改设置
```php
max_execution_time = 300
```
问题就解决了，但不知道具体是哪几个配置起了作用，有些项可能不需要，这个有待进一步的测试。

**Comment by peinhu** [comment]
@tiayo 改完配置后记得重启nginx和php-fpm服务

**Comment by tiayo** [comment]
可是我返回的错误是404诶，不是504。

**Comment by peinhu** [comment]
应该是相同原因造成的

发自我的 iPhone

**Comment by tiayo** [comment]
我没加
fastcgi_connect_timeout 300;
fastcgi_send_timeout 300;
fastcgi_read_timeout 300;
明天加上试试，其他是已经都加了不行，谢谢您！

**Comment by tiayo** [comment]
加上
fastcgi_connect_timeout 300;
fastcgi_send_timeout 300;
fastcgi_read_timeout 300;
后问题解决
