### ISSUE TITLE
上传前的hash计算是否可以关闭，有时候对文件上传质量要求不高的时候，hash计算需要太长的时间。

### ISSUE THREAD

**Issue by tiayo** [peinhu/AetherUpload-Laravel#60]

**Comment by peinhu** [comment]
可以考虑做成可选项，不开秒传的话确实上传前可以不用计算。

发自我的 iPhone

**Comment by peinhu** [comment]
不过这样就无法验证上传后的文件是否完整了，不能比对hash

发自我的 iPhone

**Comment by peinhu** [comment]
准备加个宽松模式选项，前端不计算hash，默认不启用。

发自我的 iPhone

**Comment by tiayo** [comment]
期待您的更新！

**Comment by peinhu** [comment]
v2.0.7已经加入宽松模式，具体查看配置文件的注释说明。
