### ISSUE TITLE
如果设置直接上传到服务器根目录下的某个文件夹内

### ISSUE THREAD

**Issue by Sanbingduizhang** [peinhu/AetherUpload-Laravel#61]
root_dir 这个设置上传目录，但是好像只能生成在storage下，我想放在服务器根目录下的某个文件夹内(比如/home/uploads/)
我目前是上传到默认配置文件中的root_dir设置的文件夹内，然后用Storage移动到指定目录的，
可以设置吗

**Comment by peinhu** [comment]
laravel约定一般文件上传后都是放在storage下的，而且我这边用了laravel的方法来保存文件，它默认路径就是storage下没法改。
不建议你自己手动去转移，如果你一定要放在外面，系统是linux的话，可以试试用**软连接**来实现，我没这么做过，但理论上是可行的。

**Comment by Sanbingduizhang** [comment]
因为用到了ftp服务(既可以ftp上传，也可以网页上传)。另一方面也配置了访问路径到对应的目录下面(/home/uploads,这个是可以nginx配置访问的)
现在想把网页上传的文件以及ftp上传的文件放到一起的,这样就很方面访问了。我是在文件上传之后转移文件到指定目录下的；
不过可以试试软链接这个法子；
谢谢
