### ISSUE TITLE
上传成功生成的文件目录格式

### ISSUE THREAD

**Issue by Sanbingduizhang** [peinhu/AetherUpload-Laravel#62]
class SavedPathResolver
{
    public static function encode($group, $groupSubDir, $name)
    {
        return $group . '_' . $groupSubDir . '_' . $name;
    }
}

如果这个地址的格式可以配置就更好了，既可以a_b_c.txt也可以配置成a/b/c.txt

**Comment by peinhu** [comment]
其实一开始是"/"，但反应在url地址当中层级太深了，不太美观，所以改成了"_"，你认为下划线是有什么不好吗？

**Comment by Sanbingduizhang** [comment]
'_'没什么不好，但是如果可以配置成'/'得话，就不需要把'/'转换成'_'
因为我现在是直接去通过这个地址去访问这个文件的,

**Comment by peinhu** [comment]
这个属于特殊需求，一般用不到，你自己用str_replace替换一下字符，或者调用SavedPathResolver::decode解析一下就行了，还是挺方便的。
