### ISSUE TITLE
关于Hash的判断问题

### ISSUE THREAD

**Issue by tdWarren** [peinhu/AetherUpload-Laravel#64]
if ( ConfigMapper::get('lax_mode') === false && $resourceHash !== $resourceRealHash ) {
                    throw new \Exception(trans('aetherupload::messages.upload_error'));
                }
很奇怪，为什么我上传文件一直在这个问题出错了
实际上我是直接复制例子的内容的

**Comment by peinhu** [comment]
你把$resourceHash和$resourceRealHash分别打印出来看看就知道了
```php 
dd($resourceHash.'-'.$resourceRealHash);
```

**Comment by peinhu** [comment]
抱歉，`spark-md5.min.js`现在不是**可选**而是**必需**，需要引入一下，即使不开启秒传，比对hash时也需要用到，示例中忘记改掉了。

**Comment by tdWarren** [comment]
> 抱歉，`spark-md5.min.js`现在不是**可选**而是**必需**，需要引入一下，即使不开启秒传，比对hash时也需要用到，示例中忘记改掉了。

可以的，是这个问题，谢谢大佬

**Comment by peinhu** [comment]
如果不需要秒传和完整性校验的话可以开启**宽松模式**，将配置中的lax_mode值设为true，应该就可以不引入`spark-md5.min.js`。
