### ISSUE TITLE
路由缓存(route:cache)会报错

### ISSUE THREAD

**Issue by o531** [peinhu/AetherUpload-Laravel#68]
只要运行路由缓存命令，就会抛出以下错误：
```
In Route.php line 880:
  Unable to prepare route [aetherupload] for serialization. Uses Closure.
```
我觉得仅仅为了文件上传而牺牲整个网站打开速度是不太好的。就像捡了芝麻 丢了西瓜。强烈建议优化一下。

**Comment by peinhu** [comment]
将.env文件中的环境设置为`production`试试

**Comment by o531** [comment]
试了一下 还是不行

**Comment by peinhu** [comment]
我改成production后测试是可以缓存的，闭包路由只存在于示例相关路由内，生产环境下不会启用示例相关路由，请检查自己的环境，.env文件的修改是否真的生效了。

**Comment by o531** [comment]
用了这么长时间Laravel 直到今天才发现 修改.env的环境 还得清一次缓存(cache:clear)。清完缓存就ok了
