### ISSUE TITLE
如何关闭示例页面

### ISSUE THREAD

**Issue by wzhih** [peinhu/AetherUpload-Laravel#70]
配置文件里面好像没找到这个配置

**Comment by peinhu** [comment]
生产模式下不会启用

发自我的 iPhone

**Comment by wzhih** [comment]
修改env里面的`APP_ENV`和`APP_DEBUG`，都没有作用，重启服务器也是

还需要修改什么吗？

**Comment by peinhu** [comment]
缓存了吧？clear一下

发自我的 iPhone

**Comment by wzhih** [comment]
> 缓存了吧？clear一下 发自我的 iPhone
> […](#)
> 在 2019年8月20日，15:13，wzhih ***@***.***> 写道： 修改env里面的APP_ENV和APP_DEBUG，都没有作用，重启服务器也是 还需要修改说明吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

还是不行，以下是我的操作步骤
1.修改env里面的APP_ENV和APP_DEBUG
2.运行clear
```cmd
php artisan config:clear
php artisan cache:clear
php artisan view:clear
php artisan route:clear
```
3.重启服务器

有什么问题吗

**Comment by peinhu** [comment]
是不是环境问题，用了什么常驻内存的东西？重启下相关服务试试，还不行的话那我也不知道了，根本原因就是配置没生效，按照这个来排查

发自我的 iPhone

**Comment by wzhih** [comment]
好吧
