### ISSUE TITLE
Call to undefined method AetherUpload\UploadController::validate()

### ISSUE THREAD

**Issue by guoraymon** [peinhu/AetherUpload-Laravel#71]
看了下源码，UploadController继承了\App\Http\Controllers\Controller，不存在所谓的validate方法

**Comment by peinhu** [comment]
你的\App\Http\Controllers\Controller文件中有引入ValidatesRequests这个trait吗？有的话应该是可以用validate的吧？你的laravel版本是什么？

**Comment by peinhu** [comment]
我看了下laravel从5.1到5.8都是有这个文件和ValidatesRequests的，所以理论上应该不会存在你说的情况？

**Comment by guoraymon** [comment]
> 你的\App\Http\Controllers\Controller文件中有引入ValidatesRequests这个trait吗？有的话应该是可以用validate的吧？你的laravel版本是什么？

ValidatesRequests的引用被我删掉了

**Comment by guoraymon** [comment]
最好还是别继承用户的控制器吧

**Comment by peinhu** [comment]
好吧，继承使用各种函数比较方便一点，你不喜欢可以删掉继承自己单独引入ValidatesRequests。
