### ISSUE TITLE
上传后文件后缀不应该变为小写吧， 为什么要strtolower

### ISSUE THREAD

**Issue by chanble** [peinhu/AetherUpload-Laravel#79]
现在有写大写后缀， 虽然不影响文件解析，但是在下载的时候，linux会找不到文件名， 虽然有办法解决， 感觉还是不要变动原始文件为好。

**Comment by peinhu** [comment]
后缀名一般都是小写的，这边统一小写也是为了方便管理和匹配，否则有的是JPG有的是jpg有的是jPG就乱套了，转了小写后使用插件提供的路由访问，保存的是小写名，上传后返回的也是小写名，应该不会找不到文件的？
