### ISSUE TITLE
动态配置上传目录的问题，又是我：）

### ISSUE THREAD

**Issue by DianWoung** [peinhu/AetherUpload-Laravel#8]
需求：在多个控制器中，均需调用程序包，实现各个控制器上传指定目录的功能。
问题：在config目录下的aetherupload.php文件中，注释掉UPLOAD_FILE_DIR,在控制器中使用config(['aetherupload.UPLOAD_FILE_DIR'=>'example1']);动态配置该变量，但具体测试时发现文件上传到了根目录，并未上传到指定文件夹。是我调用方式不对，还是在控制器内配置参数变量无效？

**Comment by peinhu** [comment]
@Dianwoung 覆盖配置无效的原因是我的上传插件没走你控制器对应的路由，也就是没到你的控制器，而是走的自己的路由。其实在插件设计之初我考虑的就是简化使用步骤和难度，上传文件的路径完全由插件本身来管控，不需要人为在每个控制器方法中指定，也就是在控制器方法中你不需要写任何一行跟上传相关的代码，只需要获取上传以后的文件路径就行了。插件管控的同时会提供一些获取文件必要信息的路由，所有的流程对于使用者来说是透明的，都由插件在背后实现好了。所以，说实话这个需求我之前没有特别考虑过。  

再来说说怎么解决，我已经上传成功了，简单讲一下流程吧。就是利用middleware，插件提供了初始化、展示、下载这三个中间件，但是由于上面讲的原因，我没有加上传分块时的中间件，所以你现在需要手动加一下。  
1.在配置文件config/aetherupload.php中加入一行`"MIDDLEWARE_SAVE"=>[],` ，原有的配置不用注释掉。在扩展包的routes/routes.php中的aetherupload/uploading路由也就是对应save方法的最后加上`->middleware(Config::get('aetherupload.MIDDLEWARE_SAVE'));`。  

2.在项目根目录执行`php artisan make:middleware SaveToAnotherPosition`生成中间件，然后找到这个中间件并打开，在handle方法中加入你提到的`config(['aetherupload.UPLOAD_FILE_DIR'=>'example1']);`来覆盖配置，确保这个文件夹在uploads下是存在的，如不想放在uploads下面也可再加一条aetherupload.UPLOAD_PATH的配置。  

3.在app/Http/Kernel.php的$routeMiddleware数组中加入一行`'save_to_another_position' => \App\Http\Middleware\SaveToAnotherPosition::class,`来注册刚才生成的中间件，然后到config/aetherupload.php中，将"MIDDLEWARE_UPLOAD"和"MIDDLEWARE_SAVE"都定义为`['save_to_another_position']`。如需要对应多个不同文件夹，可以在中间件中根据路由做判断。

**Comment by DianWoung** [comment]
刚开始我也是想不然就做个中间件。。。大致看懂你的意思了，等忙完了项目，我fork一个分支，自己改造改造吧！谢谢您这么详细的回复！

**Comment by peinhu** [comment]
@Dianwoung 之前也有人提过自定义上传目录，看来确实有这样的需求，等我找时间加上，或者你有好的实现方式给我提PR。

**Comment by peinhu** [comment]
分组配置功能已在v1.0.2中加入，现在无需使用中间件即可支持动态配置上传目录。

**Comment by peinhu** [comment]
分组配置功能已在v1.0.2中加入，现在无需使用中间件即可支持动态配置上传目录。
