### ISSUE TITLE
exe文件上传为无效文件

### ISSUE THREAD

**Issue by xuejiasong** [peinhu/AetherUpload-Laravel#88]
exe文件上传为无效文件

**Comment by peinhu** [comment]
https://github.com/peinhu/AetherUpload-Laravel/issues/86

**Comment by xuejiasong** [comment]
我在config文件里去除了exe，上传exe还是显示无效文件 ，是不是还有其他的设置没有弄

**Comment by peinhu** [comment]
1.注意是去除你根目录下的`config/aetherupload.php`里的exe，不是我vendor源代码里的。
2.exe可能有多种mime类型，尝试在`aetherupload.php`中的`extra_mime_types`数组中加入`'exe' => 'application/octet-stream'`。如果这样做了还不行，那你得用`mime_content_type(string $filename)`这个函数看一下你的exe文件的Mime-Type到底是什么，然后再用上面方法配置。

**Comment by xuejiasong** [comment]
试了一下 mime_content_type()这个函数好像php5.3弃用了，我用了new finfo(FILEINFO_MIME_TYPE)
得到"application/x-dosexec"，设置了以后可以了
