### ISSUE TITLE
后续是否有计划支持七牛上传？

### ISSUE THREAD

**Issue by BinZhiZhu** [peinhu/AetherUpload-Laravel#95]
如题

**Comment by peinhu** [comment]
没必要支持，直接用各种云服务商的SDK上传就行了，七牛云的应该是这个https://developer.qiniu.com/kodo/sdk/1241/php

**Comment by BinZhiZhu** [comment]
> 没必要支持，直接用各种云服务商的SDK上传就行了，七牛云的应该是这个https://developer.qiniu.com/kodo/sdk/1241/php

感谢回复，直接对接sdk也是OK的，只不过是效率问题， 所以想找轮子，因为我看到一个laravel插件是基于你这个项目来搞的 https://github.com/laravel-admin-extensions/large-file-upload

最近做一些短视频相关的项目，需要上传大量的大文件，但是有些是不支持上云的，直接upload到本地。我不应该这边提issue的，😃。
