### ISSUE TITLE
上传tgz文件提示  错误：无效的文件类型

### ISSUE THREAD

**Issue by xuncanzhe** [peinhu/AetherUpload-Laravel#96]
调试代码发现是filterByExtension函数里面的 抛出异常 throw new \Exception(trans('aetherupload::messages.invalid_resource_type'));
```php
$extensions = ConfigMapper::get('resource_extensions');
if ( empty($resourceExt) || (empty($extensions) === false && in_array($resourceExt, $extensions) === false) || in_array($resourceExt, ConfigMapper::get('forbidden_extensions')) === true ) {
     throw new \Exception(trans('aetherupload::messages.invalid_resource_type')); 
}
```
 注释掉抛出异常后可以上传。 配置选项都是初始的 `$extensions` 为空 `forbidden_extensions` 中也没有 `tgz`. 按道理应该不会触发这个判断。各位有没有遇到这个情况？

**Comment by peinhu** [comment]
原因应该是mimetype判定文件中缺少你这个后缀的映射，对于不常用的后缀文件，在配置文件中找到`'extra_mime_types' => [],`，加入相应的mime-type的映射，如`'extra_mime_types' => ['tgz' => 'application/x-compressed'],`，试试这样行不行。

**Comment by xuncanzhe** [comment]
感谢回复，修改后还是原来的问题。 我调试的时候 `$resourceExt` 是有正常值的 `tgz`。应该说明`MimeType::search` 结果是正常的。我的 AetherUpload-Laravel 版本： "version": "v2.0.7",

**Comment by peinhu** [comment]
试了下，还是那个mime类型的问题，不用注释代码，配置中改成`'extra_mime_types' => ['tgz' => 'application/x-gzip'],`问题解决。

**Comment by xuncanzhe** [comment]
谢谢，刚刚试了下加上这个是可以的。
