### ISSUE TITLE
上传相同的文件，第一个文件上传正常，第二个相同的文件上传后会得到.part文件

### ISSUE THREAD

**Issue by kokobing** [peinhu/AetherUpload-Laravel#98]
相同的图片文件上传二次
第一次正常上传，得到： 1fa20dee4af9958ac6cb4c7bd7d08061.jpg 类似这样的文件
第二次正常上传，得到：1628144614796819.jpg.part 

关闭了，'lax_mode' => true, 调用setLaxMode(true)方法，但问题依旧，仍然会得到一个.part，去掉part扩展名，上传的文件就是第一次正常上传的图片文件，字节大小一样

**Comment by peinhu** [comment]
laravel版本多少？我看能不能复现

**Comment by kokobing** [comment]
laravel 8.5 最新的版本

**Comment by peinhu** [comment]
装不了8.5，我用laravel7试了下，确实有这个问题，存在同名的话临时文件应该是要被删除的。
有两个办法：
一是将配置文件`aetherupload.php`里的秒传功能打开，instant_completion设置为true，就没有这个问题。

二是将扩展包里的`PartialResource.php`文件的rename方法稍微修改一下，改成
```php
    public function rename($completeName)
    {
        $completePath = $this->getCompletePath($completeName);

        if ( $this->disk->exists($completePath) === false ) {

            if ( $this->disk->move($this->path, $completePath) === false ) {
                throw new \Exception(trans('aetherupload::messages.rename_resource_fail'));
            }
        }
        else{ //<-新增
            $this->delete(); //<-新增
        } //<-新增
    }
```

**Comment by kokobing** [comment]
嗯嗯，好的，非常感谢！

**Comment by peinhu** [comment]
新版laravel默认使用phpredis操作redis，返回值和原来的predis不太一样，可能会报错。

如果使用秒传功能，需要在.env文件中设置一下`REDIS_CLIENT=predis`
